var dir_9c35aa8e8ae87b4b3560e37544fa0290 =
[
    [ "dlpolytopologyreader.cc", "dlpolytopologyreader_8cc.html", null ],
    [ "dlpolytopologyreader.h", "dlpolytopologyreader_8h.html", "dlpolytopologyreader_8h" ],
    [ "dlpolytrajectoryreader.cc", "dlpolytrajectoryreader_8cc.html", null ],
    [ "dlpolytrajectoryreader.h", "dlpolytrajectoryreader_8h.html", "dlpolytrajectoryreader_8h" ],
    [ "dlpolytrajectorywriter.cc", "dlpolytrajectorywriter_8cc.html", null ],
    [ "dlpolytrajectorywriter.h", "dlpolytrajectorywriter_8h.html", "dlpolytrajectorywriter_8h" ],
    [ "gmxtopologyreader.cc", "gmxtopologyreader_8cc.html", null ],
    [ "gmxtopologyreader.h", "gmxtopologyreader_8h.html", "gmxtopologyreader_8h" ],
    [ "gmxtrajectoryreader.cc", "gmxtrajectoryreader_8cc.html", null ],
    [ "gmxtrajectoryreader.h", "gmxtrajectoryreader_8h.html", "gmxtrajectoryreader_8h" ],
    [ "gmxtrajectorywriter.cc", "gmxtrajectorywriter_8cc.html", null ],
    [ "gmxtrajectorywriter.h", "gmxtrajectorywriter_8h.html", "gmxtrajectorywriter_8h" ],
    [ "groreader.cc", "groreader_8cc.html", null ],
    [ "groreader.h", "groreader_8h.html", "groreader_8h" ],
    [ "growriter.cc", "growriter_8cc.html", null ],
    [ "growriter.h", "growriter_8h.html", "growriter_8h" ],
    [ "h5mdtrajectoryreader.cc", "h5mdtrajectoryreader_8cc.html", null ],
    [ "h5mdtrajectoryreader.h", "h5mdtrajectoryreader_8h.html", "h5mdtrajectoryreader_8h" ],
    [ "lammpsdatareader.cc", "lammpsdatareader_8cc.html", "lammpsdatareader_8cc" ],
    [ "lammpsdatareader.h", "lammpsdatareader_8h.html", "lammpsdatareader_8h" ],
    [ "lammpsdumpreader.cc", "lammpsdumpreader_8cc.html", null ],
    [ "lammpsdumpreader.h", "lammpsdumpreader_8h.html", "lammpsdumpreader_8h" ],
    [ "lammpsdumpwriter.cc", "lammpsdumpwriter_8cc.html", null ],
    [ "lammpsdumpwriter.h", "lammpsdumpwriter_8h.html", "lammpsdumpwriter_8h" ],
    [ "pdbreader.cc", "pdbreader_8cc.html", null ],
    [ "pdbreader.h", "pdbreader_8h.html", "pdbreader_8h" ],
    [ "pdbwriter.cc", "pdbwriter_8cc.html", null ],
    [ "xmltopologyreader.cc", "xmltopologyreader_8cc.html", null ],
    [ "xmltopologyreader.h", "xmltopologyreader_8h.html", "xmltopologyreader_8h" ],
    [ "xyzreader.cc", "xyzreader_8cc.html", null ],
    [ "xyzwriter.cc", "xyzwriter_8cc.html", null ]
];