var searchData=
[
  ['radial_5fgrid_0',['radial_grid',['../structvotca_1_1xtp_1_1GridContainers_1_1radial__grid.html',1,'votca::xtp::GridContainers']]],
  ['random_1',['Random',['../classvotca_1_1tools_1_1Random.html',1,'votca::tools']]],
  ['rangeparser_2',['RangeParser',['../classvotca_1_1tools_1_1RangeParser.html',1,'votca::tools']]],
  ['rate_5fengine_3',['Rate_Engine',['../classvotca_1_1xtp_1_1Rate__Engine.html',1,'votca::xtp']]],
  ['rawmultiplytimings_4',['RawMultiplyTimings',['../structvotca_1_1xtp_1_1EwaldPeriodicDipoleOperator_1_1RawMultiplyTimings.html',1,'votca::xtp::EwaldPeriodicDipoleOperator']]],
  ['rdfcalculator_5',['RDFCalculator',['../classvotca_1_1csg_1_1RDFCalculator.html',1,'votca::csg']]],
  ['rdfworker_6',['RDFWorker',['../classRDFWorker.html',1,'']]],
  ['reciprocalterm_7',['ReciprocalTerm',['../structvotca_1_1xtp_1_1ewaldcontainer_1_1ReciprocalTerm.html',1,'votca::xtp::ewaldcontainer']]],
  ['reducededge_8',['ReducedEdge',['../classvotca_1_1tools_1_1ReducedEdge.html',1,'votca::tools']]],
  ['reducedgraph_9',['ReducedGraph',['../classvotca_1_1tools_1_1ReducedGraph.html',1,'votca::tools']]],
  ['region_10',['Region',['../classvotca_1_1xtp_1_1Region.html',1,'votca::xtp']]],
  ['regular_5fgrid_11',['Regular_Grid',['../classvotca_1_1xtp_1_1Regular__Grid.html',1,'votca::xtp']]],
  ['residue_12',['Residue',['../classvotca_1_1csg_1_1Residue.html',1,'votca::csg']]],
  ['ritzeigenpair_13',['RitzEigenPair',['../structvotca_1_1xtp_1_1DavidsonSolver_1_1RitzEigenPair.html',1,'votca::xtp::DavidsonSolver']]],
  ['rootcandidate_14',['RootCandidate',['../structvotca_1_1xtp_1_1qp__solver_1_1RootCandidate.html',1,'votca::xtp::qp_solver']]],
  ['rpa_15',['RPA',['../classvotca_1_1xtp_1_1RPA.html',1,'votca::xtp']]],
  ['rpa_5feigensolution_16',['rpa_eigensolution',['../structvotca_1_1xtp_1_1RPA_1_1rpa__eigensolution.html',1,'votca::xtp::RPA::rpa_eigensolution'],['../structvotca_1_1xtp_1_1RPA__UKS_1_1rpa__eigensolution.html',1,'votca::xtp::RPA_UKS::rpa_eigensolution']]],
  ['rpa_5fuks_17',['RPA_UKS',['../classvotca_1_1xtp_1_1RPA__UKS.html',1,'votca::xtp']]]
];
