var searchData=
[
  ['radial_5fgrid_0',['radial_grid',['../structvotca_1_1xtp_1_1GridContainers_1_1radial__grid.html',1,'votca::xtp::GridContainers']]],
  ['random_1',['Random',['../classvotca_1_1tools_1_1Random.html',1,'votca::tools']]],
  ['rangeparser_2',['RangeParser',['../classvotca_1_1tools_1_1RangeParser.html',1,'votca::tools']]],
  ['rate_5fengine_3',['Rate_Engine',['../classvotca_1_1xtp_1_1Rate__Engine.html',1,'votca::xtp']]],
  ['rdfcalculator_4',['RDFCalculator',['../classvotca_1_1csg_1_1RDFCalculator.html',1,'votca::csg']]],
  ['rdfworker_5',['RDFWorker',['../classRDFWorker.html',1,'']]],
  ['reducededge_6',['ReducedEdge',['../classvotca_1_1tools_1_1ReducedEdge.html',1,'votca::tools']]],
  ['reducedgraph_7',['ReducedGraph',['../classvotca_1_1tools_1_1ReducedGraph.html',1,'votca::tools']]],
  ['region_8',['Region',['../classvotca_1_1xtp_1_1Region.html',1,'votca::xtp']]],
  ['regular_5fgrid_9',['Regular_Grid',['../classvotca_1_1xtp_1_1Regular__Grid.html',1,'votca::xtp']]],
  ['residue_10',['Residue',['../classvotca_1_1csg_1_1Residue.html',1,'votca::csg']]],
  ['ritzeigenpair_11',['RitzEigenPair',['../structvotca_1_1xtp_1_1DavidsonSolver_1_1RitzEigenPair.html',1,'votca::xtp::DavidsonSolver']]],
  ['rootcandidate_12',['RootCandidate',['../structvotca_1_1xtp_1_1qp__solver_1_1RootCandidate.html',1,'votca::xtp::qp_solver']]],
  ['rpa_13',['RPA',['../classvotca_1_1xtp_1_1RPA.html',1,'votca::xtp']]],
  ['rpa_5feigensolution_14',['rpa_eigensolution',['../structvotca_1_1xtp_1_1RPA_1_1rpa__eigensolution.html',1,'votca::xtp::RPA::rpa_eigensolution'],['../structvotca_1_1xtp_1_1RPA__UKS_1_1rpa__eigensolution.html',1,'votca::xtp::RPA_UKS::rpa_eigensolution']]],
  ['rpa_5fuks_15',['RPA_UKS',['../classvotca_1_1xtp_1_1RPA__UKS.html',1,'votca::xtp']]]
];
