var searchData=
[
  ['radial_5fgrid_0',['radial_grid',['../structvotca_1_1xtp_1_1GridContainers_1_1radial__grid.html',1,'votca::xtp::GridContainers']]],
  ['random_1',['Random',['../classvotca_1_1tools_1_1Random.html',1,'votca::tools']]],
  ['rangeparser_2',['RangeParser',['../classvotca_1_1tools_1_1RangeParser.html',1,'votca::tools']]],
  ['rate_5fengine_3',['Rate_Engine',['../classvotca_1_1xtp_1_1Rate__Engine.html',1,'votca::xtp']]],
  ['rawmultiplytimings_4',['RawMultiplyTimings',['../structvotca_1_1xtp_1_1EwaldPeriodicDipoleOperator_1_1RawMultiplyTimings.html',1,'votca::xtp::EwaldPeriodicDipoleOperator']]],
  ['rdfcalculator_5',['RDFCalculator',['../classvotca_1_1csg_1_1RDFCalculator.html',1,'votca::csg']]],
  ['rdfworker_6',['RDFWorker',['../classRDFWorker.html',1,'']]],
  ['reducededge_7',['ReducedEdge',['../classvotca_1_1tools_1_1ReducedEdge.html',1,'votca::tools']]],
  ['reducedgraph_8',['ReducedGraph',['../classvotca_1_1tools_1_1ReducedGraph.html',1,'votca::tools']]],
  ['region_9',['Region',['../classvotca_1_1xtp_1_1Region.html',1,'votca::xtp']]],
  ['regular_5fgrid_10',['Regular_Grid',['../classvotca_1_1xtp_1_1Regular__Grid.html',1,'votca::xtp']]],
  ['residue_11',['Residue',['../classvotca_1_1csg_1_1Residue.html',1,'votca::csg']]],
  ['ritzeigenpair_12',['RitzEigenPair',['../structvotca_1_1xtp_1_1DavidsonSolver_1_1RitzEigenPair.html',1,'votca::xtp::DavidsonSolver']]],
  ['rootcandidate_13',['RootCandidate',['../structvotca_1_1xtp_1_1qp__solver_1_1RootCandidate.html',1,'votca::xtp::qp_solver']]],
  ['rpa_14',['RPA',['../classvotca_1_1xtp_1_1RPA.html',1,'votca::xtp']]],
  ['rpa_5feigensolution_15',['rpa_eigensolution',['../structvotca_1_1xtp_1_1RPA_1_1rpa__eigensolution.html',1,'votca::xtp::RPA::rpa_eigensolution'],['../structvotca_1_1xtp_1_1RPA__UKS_1_1rpa__eigensolution.html',1,'votca::xtp::RPA_UKS::rpa_eigensolution']]],
  ['rpa_5fuks_16',['RPA_UKS',['../classvotca_1_1xtp_1_1RPA__UKS.html',1,'votca::xtp']]],
  ['run_17',['Run',['../structvotca_1_1xtp_1_1TCMatrix__dft_1_1Run.html',1,'votca::xtp::TCMatrix_dft']]]
];
